# Generated by Django 5.1.7 on 2026-02-27 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_order_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Harakatlar jurnali', 'verbose_name_plural': 'Harakatlar jurnali'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='clinicsettings',
            options={'verbose_name': 'Klinika sozlamalari', 'verbose_name_plural': 'Klinika sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bildirishnoma', 'verbose_name_plural': 'Bildirishnomalar'},
        ),
        migrations.AlterModelOptions(
            name='notificationsettings',
            options={'verbose_name': 'Bildirishnoma sozlamalari', 'verbose_name_plural': 'Bildirishnoma sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Xizmat turi', 'verbose_name_plural': 'Xizmat turlari'},
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Botga /start yuborishdan oldin @ siz Telegram username ni shu yerga yozing (masalan: john_doe)', max_length=64, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Eslatmalar'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='clinic_name',
            field=models.CharField(default='Stomatologik klinika', max_length=200, verbose_name='Klinika nomi'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='currency',
            field=models.CharField(default='UZS', max_length=10, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qilgan"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_deadline', 'Zakaz muddati'), ('debt_reminder', 'Qarz eslatmasi'), ('system', 'Tizim')], default='system', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='debt_reminder_days',
            field=models.PositiveIntegerField(default=5, verbose_name='Qarz eslatmasi (kun)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_in_system',
            field=models.BooleanField(default=True, verbose_name='Tizimda'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_via_telegram',
            field=models.BooleanField(default=True, verbose_name='Telegram orqali'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='order_deadline_days',
            field=models.PositiveIntegerField(default=3, verbose_name='Zakaz muddati (kun)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram chat ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='blog.client', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name="Tayyor bo'lish sanasi"),
        ),
        migrations.AlterField(
            model_name='order',
            name='debt_payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name="Qarz to'lov sanasi"),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Buyurtma raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='blog.servicetype', verbose_name='Xizmat turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilindi')], default='draft', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Umumiy summa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Eslatma'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='blog.order', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="To'lov sanasi"),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('bank', 'Bank'), ('other', 'Boshqa')], default='cash', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Standart narx'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
    ]
