# Generated by Django 5.1.7 on 2026-03-04 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_telegram_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('category', models.CharField(choices=[('office', 'Ofis'), ('salary', 'Maosh'), ('equipment', 'Jihoz / uskuna'), ('utilities', 'Kommunal'), ('medication', 'Dori-darmon'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rasxod',
                'verbose_name_plural': 'Rasxodlar',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
