# Generated by Django 5.1.7 on 2026-03-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='OrderWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=2, default=100, help_text='Buyurtma summasidan ushbu ishchiga tegishli foiz (0–100)', max_digits=5, verbose_name='Ulush (%)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_workers', to='blog.order', verbose_name='Buyurtma')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_workers', to='blog.worker', verbose_name='Ishchi')),
            ],
            options={
                'verbose_name': 'Buyurtmadagi ishchi',
                'verbose_name_plural': 'Buyurtmadagi ishchilar',
                'unique_together': {('order', 'worker')},
            },
        ),
    ]
