# Generated by Django 5.1.7 on 2026-03-12 11:28

import django.db.models.deletion
from django.db import migrations, models


def create_categories_and_migrate(apps, schema_editor):
    ExpenseCategory = apps.get_model('blog', 'ExpenseCategory')
    Expense = apps.get_model('blog', 'Expense')
    # Eski turlar va yangi kategoriyalar
    defaults = [
        ('office', 'Ofis', 1),
        ('salary', 'Maosh', 2),
        ('equipment', 'Jihoz / uskuna', 3),
        ('utilities', 'Kommunal', 4),
        ('medication', 'Dori-darmon', 5),
        ('other', 'Boshqa', 6),
    ]
    cat_by_code = {}
    for code, name, order in defaults:
        c = ExpenseCategory.objects.create(name=name, order=order)
        cat_by_code[code] = c
    for exp in Expense.objects.all():
        if exp.category_old and exp.category_old in cat_by_code:
            exp.category = cat_by_code[exp.category_old]
            exp.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_add_worker_orderworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Rasxod turi',
                'verbose_name_plural': 'Rasxod turlari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='category_old',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='blog.expensecategory', verbose_name='Turi'),
        ),
        migrations.RunPython(create_categories_and_migrate, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='expense',
            name='category_old',
        ),
    ]
