from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('telegram/webhook/', views.telegram_webhook, name='telegram_webhook'),
    path('clients/', views.client_list, name='client_list'),
    path('clients/add/', views.client_create, name='client_create'),
    path('clients/<int:pk>/', views.client_detail, name='client_detail'),
    path('clients/<int:pk>/edit/', views.client_edit, name='client_edit'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/add/', views.order_create, name='order_create'),
    path('orders/<int:pk>/', views.order_detail, name='order_detail'),
    path('orders/<int:pk>/edit/', views.order_edit, name='order_edit'),
    path('orders/<int:pk>/complete/', views.order_complete, name='order_complete'),
    path('orders/<int:order_pk>/payment/add/', views.payment_add, name='payment_add'),
    path('payments/', views.payment_list, name='payment_list'),
    path('payments/<int:pk>/receipt/', views.payment_receipt, name='payment_receipt'),
    path('reports/sales/', views.report_sales, name='report_sales'),
    path('reports/sales/excel/', views.export_sales_excel, name='export_sales_excel'),
    path('reports/sales/pdf/', views.export_sales_pdf, name='export_sales_pdf'),
    path('reports/debts/', views.report_debts, name='report_debts'),
    path('reports/debts/excel/', views.export_debts_excel, name='export_debts_excel'),
    path('reports/debts/pdf/', views.export_debts_pdf, name='export_debts_pdf'),
    path('reports/analytics/', views.report_analytics, name='report_analytics'),
    path('calendar/', views.calendar_view, name='calendar'),
    path('servicetypes/', views.servicetype_list, name='servicetype_list'),
    path('servicetypes/add/', views.servicetype_create, name='servicetype_create'),
    path('servicetypes/<int:pk>/edit/', views.servicetype_edit, name='servicetype_edit'),
    path('servicetypes/<int:pk>/delete/', views.servicetype_delete, name='servicetype_delete'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('api/notification-count/', views.notification_count_api, name='notification_count_api'),
    path('notifications/<int:pk>/read/', views.notification_read, name='notification_read'),
    path('settings/', views.settings_view, name='settings'),
    path('activity-log/', views.activity_log, name='activity_log'),
]
